### PR TITLE
Implemented supporting multiple filters

### PR DESCRIPTION
**Pull request by chenfengone**
Implemented supporting multiple filters, and change the settings file to below format, it should be more reasonable:
{"funcList" : {
    "doubleSpacing": false,
    **"sort": 1,**
    "filters": [
        {
            "extensions": [
                ".LIB"
            ],
            "native": "/(?:^|^public\\s*)function\\s+\\w*/mgi",
            "display": "/((?:^|public\\s*)function\\s+\\w+)/1i"
        },
        {
            "extensions": [
                ".LIB"
            ],
            "native": "/(?:^|^public\\s*)sub\\s+\\w*/mgi",
            "display": "/((?:^|public\\s*)sub\\s+\\w+)/1i"
        }
    ]
}}

### CODE REVIEW

**Comment by qrti** [comment]
chenfengone,

thank you for your efforts to bring funcList further.

One goal would have been to show the list of filtered functions in the 
left sidebar of vscode, but at the moment I have no time for this project.


Kind Regards
Kurt


-- 

mail
mailto:qrt@qland.de

home
http://www.qland.de

youtube
http://www.youtube.com/user/qrti

github
https://github.com/qrti

**Comment by chenfengone** [comment]
qrti, wow, it's a good idea to implement this at left sidebar, will do it if i have time.

**Comment by qrti** [comment]
Chenfengone,

maybe this would make funclist a programmers must have extension ;) ...


Kind Regards
Kurt




-- 

mail
mailto:qrt@qland.de

home
http://www.qland.de

youtube
http://www.youtube.com/user/qrti

github
https://github.com/qrti

**Comment by ruocogito** [comment]
This good idea, make more list types on command palette:
show list_type1 == RegEx for functions in list_type1; custom name for list_type1
show list_type2 == RegEx for sub ...
...
RegEx for class...

**Pull request closed without merging**
